version: "2"
services:
  student_server:
    container_name: student_server
    image: minhnt95/student-server-runner
    volumes:
      - ../tmp/student-repo:/student-repo
    ports:
      - "3000:3000"
    links:
      - mongodb
    networks:
      - my-net
  mongodb:
    container_name: mongodb
    image: mongo
    #volumes:
    #  - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-net
networks:
    my-net:
      driver: bridge
