version: "2"
services:
  student_server:
    container_name: student_server
    image: minhnt95/student-server-runner
    volumes:
      - ../../tmp/student-repo:/student-repo
    ports:
      - ${STUDENT_PORT_R1}:${STUDENT_PORT_R1}
    links:
      - mongodb
    networks:
      - test-net
    environment:
      PORT: ${STUDENT_PORT_R1}
      HOST: ${STUDENT_HOST_R1}
      MONGO_PATH: ${MONGO_PATH_R1}
      MONGO_PORT: ${MONGO_PORT_R1}
  mongodb:
    container_name: mongodb
    image: mongo:3.6.12
    #volumes:
    #  - ./data:/data/db
    ports:
      - ${MONGO_HOST_PORT_R1}:${MONGO_PORT_R1}
    networks:
      - test-net
networks:
    test-net:
      driver: bridge
