version: "2"
services:
  student_server:
    container_name: student_runner_02
    image: minhnt95/student-runner-02
    volumes:
      - ../../tmp/student-repo:/student-repo
    networks:
      - test-net-02
    environment:
      STUDENT_REPO_PATH: ${STUDENT_REPO_PATH}
      STUDENT_STD_OUT_FILE: ${STUDENT_STD_OUT_FILE}
networks:
    test-net-02:
      driver: bridge
